//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ifesFood
{
    using System;
    using System.Collections.Generic;
    
    public partial class Carousel
    {
        public int Id { get; set; }
        public string Titulo { get; set; }
        public string Descricao { get; set; }
        public int ProdutoID { get; set; }
        public Nullable<bool> Destaque { get; set; }
    
        public virtual Produto Produto { get; set; }
    }
}
